/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "factorial.h"

int *
factorial_1_svc(numbers *argp, struct svc_req *rqstp)
{
	static int  result=1;

	   printf("factorial(%d) is called\n",argp->a);
	   for(int i=1;i<=argp->a;i++)  result=result*i;
	   
	return &result;
}
